### PR TITLE
Cmatrix color config

### PR DESCRIPTION
**Pull request by b1ten**
I added a way to customize cmatrix colors, both fg and bg (bg works a bit quirky, but i found it quite cool nevertheless.).

### CODE REVIEW

**Comment by AnErrupTion** [comment]
@b1ten This is essentially a duplicate of #554 but with a way of customizing the background color. Given that I'm merging the Zig rewrite sooner rather than later, I'm not going to merge this (nor the other one) now. How do you feel about the idea of rebasing the PR around Zig when it's merged? (cc. @MatthiasQuintern)

**Comment by b1ten** [comment]
I will give it a try, never used Zig before so it'll be quite interessting.

**Comment by tmkcell** [comment]
Any news on this?

**Comment by AnErrupTion** [comment]
@b1ten Your PR was half superseded by #652. I'm going to close yours (since it hasn't been updated thus far), but of course, feel free to reopen one with the other half of the changes!

**Pull request closed without merging**
