### PR TITLE
Center the environment name.

### PR DESCRIPTION
**Pull request by llc0930**

### CODE REVIEW

**Comment by AnErrupTion** [comment]
@llc0930 It certainly makes it look a bit odd since the username & password fields aren't centered either, which is why I do think this is best made a config option.

**Comment by llc0930** [comment]
Modify it after some time.

**Comment by llc0930** [comment]
zig doesn't seem to support optional arguments? So the way I wrote it might be a little ugly.

**Review by AnErrupTion — APPROVED** [review]
LGTM. Thanks for your contribution!

**Pull request merged**
